apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce.fullname" . }}-user-service
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
    app.kubernetes.io/component: user-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.ports.userService }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ecommerce.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: user-service