apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "hooks-demo.fullname" . }}-cleanup"
  labels:
    {{- include "hooks-demo.labels" . | nindent 4 }}
  annotations:
    # Run after all resources are deleted
    "helm.sh/hook": post-delete
    # Execute last
    "helm.sh/hook-weight": "1"
    # Delete cleanup job after success
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ include "hooks-demo.fullname" . }}-cleanup"
    spec:
      restartPolicy: Never
      containers:
      - name: cleanup
        image: alpine:3.16
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting cleanup process..."
          echo "Release: {{ .Release.Name }}"
          echo "Namespace: {{ .Release.Namespace }}"
          
          # Simulate cleanup tasks
          echo "Cleaning up external resources..."
          echo "- Removing S3 buckets..."
          sleep 2
          echo "- Deleting DNS records..."
          sleep 2
          echo "- Revoking API keys..."
          sleep 2
          echo "- Cleaning up monitoring dashboards..."
          sleep 2
          
          echo "Cleanup completed successfully!"
          echo "All external resources have been removed."