# Development environment overrides
app:
  environment: development

replicaCount: 1

image:
  tag: "latest"

service:
  type: ClusterIP

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

database:
  host: dev-postgres.local

env:
  - name: LOG_LEVEL
    value: debug
  - name: DEBUG
    value: "true"