# Production environment overrides
app:
  environment: production

replicaCount: 5

image:
  tag: "1.4"  # Stable version

service:
  type: LoadBalancer

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: myapp.company.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: myapp-tls
      hosts:
        - myapp.company.com

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

database:
  host: prod-postgres.company.com
  port: 5432

redis:
  enabled: true
  host: prod-redis.company.com

env:
  - name: LOG_LEVEL
    value: warn
  - name: DEBUG
    value: "false"