# Staging environment overrides
app:
  environment: staging

replicaCount: 2

image:
  tag: "1.5"

service:
  type: ClusterIP

ingress:
  enabled: true
  hosts:
    - host: myapp-staging.company.com
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

database:
  host: staging-postgres.company.com

redis:
  enabled: true
  host: staging-redis.company.com

env:
  - name: LOG_LEVEL
    value: info
  - name: DEBUG
    value: "false"